In [1]:
import numpy as np

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
address = "/content/drive/My Drive/Colab Notebooks/MD/PROBLEM3.data"

In [4]:
# This function uses given data to extract a list of particle coordinates
def readLocation(fileAddress):
    txt = open(fileAddress, "r")

    coordinates = []

    for x in txt:
        # print(x)
        if x[0] != "#":
            temp = x.split()
            location = np.array([float(temp[0]), float(temp[1]), float(temp[2])])
            # print(velocity)
            coordinates.append(location)

    return np.array(coordinates)

In [5]:
# list of coordinates of all the particles in system
locs = readLocation(address)

In [6]:
# Update function takes current state to next state
# Obeying Periodic Boundary Condition

def update(arr, l):
    # 'nudge' is the matrix that contains the changes
    # to be done in coordinates of particles to take
    # them to a new state. Norm is taken to ensure
    # 1 unit displacement in any random direction
    nudge = np.random.rand(len(arr), 3) 
    
    for i in range(len(arr)):
        nudge[i] = nudge[i]/np.linalg.norm(nudge[i])
        arr[i] = arr[i] + nudge[i]

        # Checking the Boundary condition
        if arr[i][0] >= l/2: arr[i][0] = arr[i][0] - l 
        if arr[i][0] < -l/2: arr[i][0] = arr[i][0] + l 
        if arr[i][1] >= l/2: arr[i][1] = arr[i][1] - l 
        if arr[i][1] < -l/2: arr[i][1] = arr[i][1] + l
        if arr[i][2] >= l/2: arr[i][2] = arr[i][2] - l 
        if arr[i][2] < -l/2: arr[i][2] = arr[i][2] + l 
    
#     arr = np.array(arr)
    return np.array(arr)

In [7]:
# length of the box
l = 18.64

# number of iterations
its = 10

In [8]:
states = []
states.append(locs)

for i in range(its):
    states.append(update(states[i], l))
    #print("max coordinate of state {} is: {}".format(i, np.amax(states[i])))

print(states[10])

[[-6.38483915e+00 -4.55352871e+00  1.91819436e+00]
 [ 5.30408773e+00 -9.17985360e+00 -4.86855652e+00]
 [-3.81073266e+00 -7.95986500e+00 -5.50933596e+00]
 [-4.27125303e-03  2.07952919e+00 -7.20684487e+00]
 [-2.34251299e+00  5.67586807e-01  1.20790448e+00]
 [ 4.81499346e+00  4.10206408e+00 -6.90875723e+00]
 [-1.16862077e+00 -8.23829824e+00  1.76319260e-01]
 [ 4.91503671e-01  8.81793440e+00 -1.64341140e+00]
 [-7.69020546e+00  3.74867587e+00  7.67534475e+00]
 [-3.14920182e+00 -5.99853758e-01  1.43549595e-01]
 [-1.86524851e+00  6.21326072e+00  7.24950674e-01]
 [-3.83470927e+00  1.51294195e+00  6.35151555e+00]
 [ 6.87811979e+00  6.95822897e+00 -5.42417272e+00]
 [-5.54772887e+00 -1.18279953e+00  6.97736691e+00]
 [-3.75291591e+00  8.61943362e+00 -2.34385681e+00]
 [-5.66070512e+00  7.24206956e-01  4.45954038e+00]
 [-8.86794291e+00 -2.00473591e+00  1.10744776e+00]
 [ 4.51335102e-01  8.59166843e+00 -7.56569662e+00]
 [-7.50520010e+00  3.00170473e+00 -5.59681314e+00]
 [-6.61839207e+00  2.30363796e-

In [9]:
# # Saving the 2D array in a text file
# file = open("out.txt", "w+")
# file.write("# The coordinates of particles after 10 iterations: \n")

# for x in states[10]:
#     file.write(str(x[0])[:8] + "       " + str(x[1])[:8] + "       " + str(x[2])[:8] + "\n")