In [1]:
import numpy as np

In [2]:
address = "/Users/nishxntyxdxv/Desktop/sem7/Computational-Chemistry-Lab/Lab4/PROBLEM3.data"

In [3]:
# This function uses given data to extract a list of particle coordinates
def readLocation(fileAddress):
    txt = open(fileAddress, "r")

    coordinates = []

    for x in txt:
        # print(x)
        if x[0] != "#":
            temp = x.split()
            location = np.array([float(temp[0]), float(temp[1]), float(temp[2])])
            # print(velocity)
            coordinates.append(location)
            
    return np.array(coordinates)

In [4]:
# Update function takes current state to next state
# Obeying Periodic Boundary Condition

def update(arr, l):
    # 'nudge' is the matrix that contains the changes
    # to be done in coordinates of particles to take
    # them to a new state. Norm is taken to ensure
    # 1 unit displacement in any random direction
    nudge = np.linalg.norm(np.random.rand(216, 3))
    arr = arr + nudge
    
    for i in arr:
        # Checking the Boundary condition
        if i[0] >= l/2: i[0] = i[0] - l 
        if i[0] < -l/2: i[0] = i[0] + l 
        if i[1] >= l/2: i[1] = i[1] - l 
        if i[1] < -l/2: i[1] = i[1] + l
        if i[2] >= l/2: i[2] = i[2] - l 
        if i[2] < -l/2: i[2] = i[2] + l 
    
#     arr = np.array(arr)
    return arr

In [5]:
# list of coordinates of all the particles in system
locs = readLocation(address)

In [6]:
# length of the box
l = 18.64

# number of iterations
its = 10

In [7]:
states = []
states.append(locs)

for i in range(1, its + 1):
    states.append(update(states[i - 1], l))
    #print("max coordinate of state {} is: {}".format(i, np.amax(states[i])))

In [10]:
print(states[10])

[[ 4.78833672  7.44583772 -5.82356228]
 [-2.93956328  1.33772772  8.39146772]
 [-9.20416128  1.85883772  5.58293772]
 [-5.50536328 -7.08096328  4.49203672]
 [ 8.19513872 -5.48036328 -5.63346228]
 [-2.09383528 -3.51771228  3.98403772]
 [-6.73036328  2.68393772 -8.10356128]
 [-5.57596228  0.46889772  8.94309772]
 [ 2.69106772 -1.86456328 -0.33268228]
 [ 8.39413672 -7.21276028 -7.68806128]
 [ 8.56263772 -2.03296028 -5.67236128]
 [ 8.72133772 -6.06040228 -1.18636128]
 [-0.08346128 -0.49968228  5.78553672]
 [ 5.83593772 -8.65770228 -0.04896328]
 [ 7.89023872  1.58253472  7.91175772]
 [ 7.14417772 -7.11642228 -3.65960228]
 [ 1.46273772 -8.58326128 -5.59060228]
 [-7.66687228  2.79663872  2.99963772]
 [ 4.59753772 -5.58066128  6.53423672]
 [ 4.44613672 -7.80989228 -2.63175628]
 [ 3.45043772  0.28443772 -5.46616128]
 [-3.51518228 -0.86986128 -1.26116128]
 [ 6.35983772  5.35870772 -9.11398228]
 [ 5.18773672 -3.26056128 -0.33136328]
 [-6.98896228 -3.91691228  7.21074872]
 [ 5.60992772  1.54383772

In [9]:
# Saving the 2D array in a text file

file = open("out.txt", "w+")
file.write("# The coordinates of particles after 10 iterations: \n")
for x in states[10]:
    file.write(str(x[0])[:8] + "       " + str(x[1])[:8] + "       " + str(x[2])[:8] + "\n")